FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY src ./src

RUN npx prisma generate && npm prune --omit=dev

ENV NODE_ENV=production
EXPOSE 5000

CMD ["node", "src/server.js"]
